/**
 * Autogenerated base Hooks module from urn-cli
 *
 * @packageDocumentation
 */

import * as uranio from "../cln/main";

export const hooks = {
	superusers: {
		find: async (options?: uranio.types.HookArguments<"superuser", "find">) => {
			const args: uranio.types.HookArguments<"superuser", "find"> = {
				...options,
			};
			return await uranio.base.create("superuser").hook("find")(args);
		},
		find_id: async (
			id: string,
			options?: uranio.types.HookArguments<"superuser", "find_id">
		) => {
			const args: uranio.types.HookArguments<"superuser", "find_id"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("superuser").hook("find_id")(args);
		},
		find_one: async (
			options?: uranio.types.HookArguments<"superuser", "find_one">
		) => {
			const args: uranio.types.HookArguments<"superuser", "find_one"> = {
				...options,
			};
			return await uranio.base.create("superuser").hook("find_one")(args);
		},
		insert: async (
			options?: uranio.types.HookArguments<"superuser", "insert">
		) => {
			const args: uranio.types.HookArguments<"superuser", "insert"> = {
				...options,
			};
			return await uranio.base.create("superuser").hook("insert")(args);
		},
		update: async (
			id: string,
			options?: uranio.types.HookArguments<"superuser", "update">
		) => {
			const args: uranio.types.HookArguments<"superuser", "update"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("superuser").hook("update")(args);
		},
		delete: async (
			id: string,
			options?: uranio.types.HookArguments<"superuser", "delete">
		) => {
			const args: uranio.types.HookArguments<"superuser", "delete"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("superuser").hook("delete")(args);
		},
	},
	users: {
		find: async (options?: uranio.types.HookArguments<"user", "find">) => {
			const args: uranio.types.HookArguments<"user", "find"> = {
				...options,
			};
			return await uranio.base.create("user").hook("find")(args);
		},
		find_id: async (
			id: string,
			options?: uranio.types.HookArguments<"user", "find_id">
		) => {
			const args: uranio.types.HookArguments<"user", "find_id"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("user").hook("find_id")(args);
		},
		find_one: async (
			options?: uranio.types.HookArguments<"user", "find_one">
		) => {
			const args: uranio.types.HookArguments<"user", "find_one"> = {
				...options,
			};
			return await uranio.base.create("user").hook("find_one")(args);
		},
		insert: async (options?: uranio.types.HookArguments<"user", "insert">) => {
			const args: uranio.types.HookArguments<"user", "insert"> = {
				...options,
			};
			return await uranio.base.create("user").hook("insert")(args);
		},
		update: async (
			id: string,
			options?: uranio.types.HookArguments<"user", "update">
		) => {
			const args: uranio.types.HookArguments<"user", "update"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("user").hook("update")(args);
		},
		delete: async (
			id: string,
			options?: uranio.types.HookArguments<"user", "delete">
		) => {
			const args: uranio.types.HookArguments<"user", "delete"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("user").hook("delete")(args);
		},
	},
	groups: {
		find: async (options?: uranio.types.HookArguments<"group", "find">) => {
			const args: uranio.types.HookArguments<"group", "find"> = {
				...options,
			};
			return await uranio.base.create("group").hook("find")(args);
		},
		find_id: async (
			id: string,
			options?: uranio.types.HookArguments<"group", "find_id">
		) => {
			const args: uranio.types.HookArguments<"group", "find_id"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("group").hook("find_id")(args);
		},
		find_one: async (
			options?: uranio.types.HookArguments<"group", "find_one">
		) => {
			const args: uranio.types.HookArguments<"group", "find_one"> = {
				...options,
			};
			return await uranio.base.create("group").hook("find_one")(args);
		},
		insert: async (options?: uranio.types.HookArguments<"group", "insert">) => {
			const args: uranio.types.HookArguments<"group", "insert"> = {
				...options,
			};
			return await uranio.base.create("group").hook("insert")(args);
		},
		update: async (
			id: string,
			options?: uranio.types.HookArguments<"group", "update">
		) => {
			const args: uranio.types.HookArguments<"group", "update"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("group").hook("update")(args);
		},
		delete: async (
			id: string,
			options?: uranio.types.HookArguments<"group", "delete">
		) => {
			const args: uranio.types.HookArguments<"group", "delete"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("group").hook("delete")(args);
		},
	},
	errors: {
		find: async (options?: uranio.types.HookArguments<"error", "find">) => {
			const args: uranio.types.HookArguments<"error", "find"> = {
				...options,
			};
			return await uranio.base.create("error").hook("find")(args);
		},
		find_id: async (
			id: string,
			options?: uranio.types.HookArguments<"error", "find_id">
		) => {
			const args: uranio.types.HookArguments<"error", "find_id"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("error").hook("find_id")(args);
		},
		find_one: async (
			options?: uranio.types.HookArguments<"error", "find_one">
		) => {
			const args: uranio.types.HookArguments<"error", "find_one"> = {
				...options,
			};
			return await uranio.base.create("error").hook("find_one")(args);
		},
		insert: async (options?: uranio.types.HookArguments<"error", "insert">) => {
			const args: uranio.types.HookArguments<"error", "insert"> = {
				...options,
			};
			return await uranio.base.create("error").hook("insert")(args);
		},
		update: async (
			id: string,
			options?: uranio.types.HookArguments<"error", "update">
		) => {
			const args: uranio.types.HookArguments<"error", "update"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("error").hook("update")(args);
		},
		delete: async (
			id: string,
			options?: uranio.types.HookArguments<"error", "delete">
		) => {
			const args: uranio.types.HookArguments<"error", "delete"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("error").hook("delete")(args);
		},
	},
	requests: {
		find: async (options?: uranio.types.HookArguments<"request", "find">) => {
			const args: uranio.types.HookArguments<"request", "find"> = {
				...options,
			};
			return await uranio.base.create("request").hook("find")(args);
		},
		find_id: async (
			id: string,
			options?: uranio.types.HookArguments<"request", "find_id">
		) => {
			const args: uranio.types.HookArguments<"request", "find_id"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("request").hook("find_id")(args);
		},
		find_one: async (
			options?: uranio.types.HookArguments<"request", "find_one">
		) => {
			const args: uranio.types.HookArguments<"request", "find_one"> = {
				...options,
			};
			return await uranio.base.create("request").hook("find_one")(args);
		},
		insert: async (
			options?: uranio.types.HookArguments<"request", "insert">
		) => {
			const args: uranio.types.HookArguments<"request", "insert"> = {
				...options,
			};
			return await uranio.base.create("request").hook("insert")(args);
		},
		update: async (
			id: string,
			options?: uranio.types.HookArguments<"request", "update">
		) => {
			const args: uranio.types.HookArguments<"request", "update"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("request").hook("update")(args);
		},
		delete: async (
			id: string,
			options?: uranio.types.HookArguments<"request", "delete">
		) => {
			const args: uranio.types.HookArguments<"request", "delete"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("request").hook("delete")(args);
		},
	},
	mykarts: {
		find: async (options?: uranio.types.HookArguments<"mykart", "find">) => {
			const args: uranio.types.HookArguments<"mykart", "find"> = {
				...options,
			};
			return await uranio.base.create("mykart").hook("find")(args);
		},
		myroute: async (
			options?: uranio.types.HookArguments<"mykart", "myroute">
		) => {
			const args: uranio.types.HookArguments<"mykart", "myroute"> = {
				...options,
			};
			return await uranio.base.create("mykart").hook("myroute")(args);
		},
		find_id: async (
			id: string,
			options?: uranio.types.HookArguments<"mykart", "find_id">
		) => {
			const args: uranio.types.HookArguments<"mykart", "find_id"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("mykart").hook("find_id")(args);
		},
		find_one: async (
			options?: uranio.types.HookArguments<"mykart", "find_one">
		) => {
			const args: uranio.types.HookArguments<"mykart", "find_one"> = {
				...options,
			};
			return await uranio.base.create("mykart").hook("find_one")(args);
		},
		insert: async (
			options?: uranio.types.HookArguments<"mykart", "insert">
		) => {
			const args: uranio.types.HookArguments<"mykart", "insert"> = {
				...options,
			};
			return await uranio.base.create("mykart").hook("insert")(args);
		},
		update: async (
			id: string,
			options?: uranio.types.HookArguments<"mykart", "update">
		) => {
			const args: uranio.types.HookArguments<"mykart", "update"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("mykart").hook("update")(args);
		},
		delete: async (
			id: string,
			options?: uranio.types.HookArguments<"mykart", "delete">
		) => {
			const args: uranio.types.HookArguments<"mykart", "delete"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("mykart").hook("delete")(args);
		},
	},
	karts: {
		find: async (options?: uranio.types.HookArguments<"kart", "find">) => {
			const args: uranio.types.HookArguments<"kart", "find"> = {
				...options,
			};
			return await uranio.base.create("kart").hook("find")(args);
		},
		mycustom: async (
			id: string,
			date: string,
			options?: uranio.types.HookArguments<"kart", "mycustom">
		) => {
			const args: uranio.types.HookArguments<"kart", "mycustom"> = {
				params: {
					id: id,
					date: date,
				},
				...options,
			};
			return await uranio.base.create("kart").hook("mycustom")(args);
		},
		find_id: async (
			id: string,
			options?: uranio.types.HookArguments<"kart", "find_id">
		) => {
			const args: uranio.types.HookArguments<"kart", "find_id"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("kart").hook("find_id")(args);
		},
		find_one: async (
			options?: uranio.types.HookArguments<"kart", "find_one">
		) => {
			const args: uranio.types.HookArguments<"kart", "find_one"> = {
				...options,
			};
			return await uranio.base.create("kart").hook("find_one")(args);
		},
		insert: async (options?: uranio.types.HookArguments<"kart", "insert">) => {
			const args: uranio.types.HookArguments<"kart", "insert"> = {
				...options,
			};
			return await uranio.base.create("kart").hook("insert")(args);
		},
		update: async (
			id: string,
			options?: uranio.types.HookArguments<"kart", "update">
		) => {
			const args: uranio.types.HookArguments<"kart", "update"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("kart").hook("update")(args);
		},
		delete: async (
			id: string,
			options?: uranio.types.HookArguments<"kart", "delete">
		) => {
			const args: uranio.types.HookArguments<"kart", "delete"> = {
				params: {
					id: id,
				},
				...options,
			};
			return await uranio.base.create("kart").hook("delete")(args);
		},
	},
} as const;
